### ISSUE TITLE
RestAPI

### ISSUE THREAD

**Issue by Hrushon** [moodbeat/back#33]
Предложения на **будущее** по проекту в частности и по API

1. Вопрос по мероприятиям - надо мне кажется подумать, решить и что-то реализовать по поводу прошедших мероприятий. Либо это пусть будет фильтр в кверисет, чтоб прошедшие мероприятия по GET-запросу не возвращались. Либо чистить периодически записи - наряду с уведомлениями. Не вижу смысла хранить старые мероприятия и возвращать всю эту портянку пользователю.
2. Также по мероприятиям - для роли employee может реализовать доп. фильтр - чтоб выходили только его мероприятия? Может я слепой, но почему-то не увидел этого... Такое чувство, судя по коду, что работнику вываливается список мероприятий и собраний, к которым он даже не причастен.
3. В swagger-e по обращению к эндпоинту socials/specialists/ кажет, что вернется одна запись, а по факту - там список. Тоже самое socials/help_types/.

**Comment by AleksandrUsolcev** [comment]
1. Да, хороше замечание. Сделаю тогда по умолчанию вывод мероприятий без учета тех, чей end_time был до сегодняшнего дня. Добавлю еще фильтр для показа уже только прошедших мероприятий, на случай если когда-нибудь на фронте например будет кнопка "Показать прошедшие".
2, 3. Тоже поправлю в ближ обнове.

**Comment by AleksandrUsolcev** [comment]
https://github.com/moodbeat/back/pull/36
